### ISSUE TITLE
CMake compile issue

### ISSUE THREAD

**Issue by darius513** [ParCoreLab/CPU-Free-model#2]
When I installed the required dependencies (including nvshmem) and ran cmake I encountered the problem in the picture below, have you encountered it?
<img width="701" alt="截屏2023-12-22 15 26 46" src="https://github.com/ParCoreLab/CPU-Free-model/assets/41977784/1ae35c8b-5acf-4146-afd1-863b83c0c729">

**Comment by kylosus** [comment]
Make sure you installed NVSHMEM with cmake support and it's in somewhere cmake can find. The package on spack is a bit behind, so if you used that to install dependencies you can either manually compile NVSHMEM and copy `NVSHMEM_HOME/lib/cmake` to the spack dir or use [this branch](https://github.com/spack/spack/pull/36363).

**Comment by darius513** [comment]
Thanks for the reply, I'll try to manually compile NVSHMEM.
