### ISSUE TITLE
Issue regarding running on Single node Multi GPU

### ISSUE THREAD

**Issue by darius513** [ParCoreLab/CPU-Free-model#3]
I am launching a program on a single machine with two GPUs, and it seems that MPI_Comm_split_type did not successfully split the communicator into subcommunicators. In the end, both processes are executing on device 0. Please see the attached screenshot for reference. Looking forward to your response.
<img width="637" alt="截屏2024-01-05 17 16 11" src="https://github.com/ParCoreLab/CPU-Free-model/assets/41977784/58c23519-29cc-4169-aef7-429cbc6c0db0">

**Comment by kylosus** [comment]
That's very odd and I wasn't able to replicate it on my machine. Can you try a different MPI version or implementation? You can also remove the split communicator code and use ranks insted to set GPUs for a single-node run.

**Comment by darius513** [comment]
This issue occurs under OpenMPI 4.1.5 with PMIx 4.2.3 and can be resolved by switching to PMIx 4.2.2. Please refer to this GitHub [issue](https://github.com/open-mpi/ompi/issues/11585) in the OpenMPI repository for more information.
