### ISSUE TITLE
Typo in the spack command

### ISSUE THREAD

**Issue by AndrewMorgan2** [ParCoreLab/CPU-Free-model#4]
Just a simple typo in the spack install command: 
$ spack install nvshmem +gpu_initiated_suppot +cuda +gdrcopy +ucx +mpi ^openmpi +cuda fabrics=ucx ^ucx +cuda +gdrcopy +dm +thread_multiple
just needs an "r" in support so:
$ spack install nvshmem +gpu_initiated_support +cuda +gdrcopy +ucx +mpi ^openmpi +cuda fabrics=ucx ^ucx +cuda +gdrcopy +dm +thread_multiple

**Comment by kylosus** [comment]
Thanks a lot for letting us know. I have fixed the typo.
